//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 2 images.
  struct image {
    /// Image `ic_favorite_border`.
    static let ic_favorite_border = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_favorite_border")
    /// Image `ic_favorite`.
    static let ic_favorite = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_favorite")
    
    /// `UIImage(named: "ic_favorite", bundle: ..., traitCollection: ...)`
    static func ic_favorite(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_favorite, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_favorite_border", bundle: ..., traitCollection: ...)`
    static func ic_favorite_border(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_favorite_border, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 3 nibs.
  struct nib {
    /// Nib `NewsFeedSectionFooter`.
    static let newsFeedSectionFooter = _R.nib._NewsFeedSectionFooter()
    /// Nib `NewsFeedSectionHeader`.
    static let newsFeedSectionHeader = _R.nib._NewsFeedSectionHeader()
    /// Nib `NewsFeedTableViewHeader`.
    static let newsFeedTableViewHeader = _R.nib._NewsFeedTableViewHeader()
    
    /// `UINib(name: "NewsFeedSectionFooter", in: bundle)`
    static func newsFeedSectionFooter(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.newsFeedSectionFooter)
    }
    
    /// `UINib(name: "NewsFeedSectionHeader", in: bundle)`
    static func newsFeedSectionHeader(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.newsFeedSectionHeader)
    }
    
    /// `UINib(name: "NewsFeedTableViewHeader", in: bundle)`
    static func newsFeedTableViewHeader(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.newsFeedTableViewHeader)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    struct _NewsFeedSectionFooter: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "NewsFeedSectionFooter"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> NewsFeedSectionFooterView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? NewsFeedSectionFooterView
      }
      
      fileprivate init() {}
    }
    
    struct _NewsFeedSectionHeader: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "NewsFeedSectionHeader"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> NewsFeedSectionHeaderView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? NewsFeedSectionHeaderView
      }
      
      fileprivate init() {}
    }
    
    struct _NewsFeedTableViewHeader: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "NewsFeedTableViewHeader"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> NewsFeedTableViewHeader? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? NewsFeedTableViewHeader
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard {
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
